name: Restart Container

on: workflow_dispatch

jobs:
  restart:
    name: Restart Container
    
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Restart container over ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_RSA_KEY }}
          script: docker compose restart ${{secrets.PROJECT_PATH }}
